<a href="https://colab.research.google.com/github/shahriar00/Machine-Learning/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Regression Algorithm**

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
data = pd.read_csv('data.csv')
data


area   price
0  1600   55000
1  3000   56500
2  3200   61000
3  3600   68000
4  4000   72000
5  5000   71000
6  2500   40000
7  2700   38000
8  1200   17000
9  5000  100000

In [12]:
data.head(6)
data.shape

(10, 2)

In [13]:
x = data[['area']]
y = data['price']

In [ ]:
plt.scatter(data['area'],data['price'],color='blue')


**Data Training Part and Testing data ready for the learning algorithm.**

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)



from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(x_train,y_train)
linear.predict(x_test)


array([51607.68147999, 58996.83289765, 64908.15403177])

In [32]:
linear.coef_

array([14.77830284])

In [33]:
linear.intercept_

11706.263824653135

In [34]:
linear.predict([[3900]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([69341.64488236])

In [36]:
y =14.77*3900+11706.263824653135

y

69309.26382465314

**Car Driving Risk analysis**

In [45]:
data1 = pd.read_csv('car driving risk analysis.csv')
data1

speed  risk
0     200    95
1      90    20
2     300    98
3     110    60
4     240    72
5     115    10
6      50     7
7     230    85
8     190    45
9     260    91
10    290    82
11    185    59
12    310    93
13     95    18
14     30     2

In [46]:
x1 = data1[['speed']]
y1 = data1['risk']



In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y1,test_size=0.30)


y_test

# from sklearn.linear_model import LinearRegression
# car = LinearRegression()

# car.fit(x_train,y_train)
# car.predict(x_test)
# car.score(x_test,y_test)